#!/bin/bash
# activate virtualenv, run migrations and touch uwsgi to reload the application server.
echo "updating proxy app"
source /srv/wnf-proxy-app/env/bin/activate && \
python /srv/wnf-proxy-app/app/manage.py migrate && \
sudo service uwsgi restart && \
sudo service nginx restart